// ADMIN-DATA — gestionado desde el panel /admin.html
// No editar manualmente si usás el panel de administración
const ADMIN_DATA = {
  "lastUpdated": "2026-06-20T23:06:44.021Z",
  "lineups": {
    "Fecha 10": {
      "titulares": [
        {
          "name": "Jubin",
          "pos": "POR"
        },
        {
          "name": "Enzo",
          "pos": "DFD"
        },
        {
          "name": "Juli Rios",
          "pos": "DFC"
        },
        {
          "name": "Mati",
          "pos": "DFC"
        },
        {
          "name": "Brandon",
          "pos": "DFI"
        },
        {
          "name": "Vidal",
          "pos": "MD"
        },
        {
          "name": "Pato",
          "pos": "MC"
        },
        {
          "name": "Sena",
          "pos": "MC"
        },
        {
          "name": "Franco F",
          "pos": "MI"
        },
        {
          "name": "Mandinga",
          "pos": "DC"
        },
        {
          "name": "Elias",
          "pos": "DC"
        }
      ],
      "suplentes": [
        {
          "name": "Vicente",
          "pos": ""
        },
        {
          "name": "Lolo",
          "pos": ""
        },
        {
          "name": "Pata",
          "pos": ""
        },
        {
          "name": "Lucas Godoy",
          "pos": ""
        },
        {
          "name": "Andres Guerra",
          "pos": ""
        }
      ]
    },
    "Fecha 11": {
      "titulares": [
        {
          "name": "Jubin",
          "pos": "POR"
        },
        {
          "name": "Seba B",
          "pos": "DFD"
        },
        {
          "name": "Mati",
          "pos": "DFC"
        },
        {
          "name": "Vicente",
          "pos": "DFC"
        },
        {
          "name": "Brandon",
          "pos": "DFI"
        },
        {
          "name": "Lucas Godoy",
          "pos": "MD"
        },
        {
          "name": "Franco F",
          "pos": "MC"
        },
        {
          "name": "Pato",
          "pos": "MC"
        },
        {
          "name": "Mandinga",
          "pos": "MI"
        },
        {
          "name": "Elias",
          "pos": "DC"
        },
        {
          "name": "Negrin",
          "pos": "DC"
        }
      ],
      "suplentes": [
        {
          "name": "Diego",
          "pos": ""
        },
        {
          "name": "Lolo",
          "pos": ""
        },
        {
          "name": "Franco Irri",
          "pos": ""
        }
      ]
    }
  },
  "igStats": {
    "posts": 85,
    "seguidores": 234,
    "siguiendo": 34
  },
  "matchResults": {
    "Fecha 10": {
      "gf": 4,
      "gc": 1,
      "type": "W",
      "rival": "Capitol F.C."
    },
    "Fecha 11": {
      "gf": 3,
      "gc": 2,
      "type": "W",
      "rival": "La Favela FC"
    }
  },
  "nextMatch": {
    "fechaNum": "11",
    "rival": "La Favela FC",
    "date": "",
    "time": "",
    "cancha": "",
    "rivalPos": 9,
    "rivalPts": 9,
    "interPos": 3,
    "interPts": 22
  },
  "scorersByMatch": {
    "amistoso": [
      "Elias x4",
      "Pata x1",
      "Mandinga x1"
    ],
    "f1": [
      "Seba T x1"
    ],
    "f2": [
      "Elias x1",
      "Seba T x1",
      "Sena x1"
    ],
    "f3": [
      "Mandinga x1"
    ],
    "f4": [
      "Elias x1"
    ],
    "f5": [
      "Elias x1",
      "Facu Munchs x1"
    ],
    "f6": [
      "Pato x1",
      "Sena x1",
      "Elias x1",
      "Facu Munchs x2",
      "Andres Guerra x2"
    ],
    "f7": [
      "Elias x3",
      "Sena x1",
      "Andres Guerra x1",
      "Diego x1"
    ],
    "f8": [
      "Mandinga x1",
      "Franco F x1"
    ],
    "f9": [
      "Sena x1",
      "Mandinga x1"
    ],
    "Fecha 10": [
      "Elias x2",
      "Lucas Godoy x1",
      "Mandinga x1"
    ],
    "Fecha 11": [
      "Franco F x1",
      "Diego x1",
      "Lucas Godoy x1"
    ]
  },
  "playerPhotos": {
    "Andres Guerra": [
      "assets/fotos/f6/Martin Sena, Andres Guerra, Facundo Munchs, Brandon Almenarez y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f7/Agustin Rebollo, Lorenzo Camara y Andres Guerra.jpg",
      "assets/fotos/f7/Andres Guerra y Lucas Vidal.jpg",
      "assets/fotos/f7/Andres Guerra, Lucas Vidal, Martin Sena, Matias Gonzalez y Diego Friedrich.jpg",
      "assets/fotos/f7/Facundo Munchs, Ezequiel Muñoz y Andres Guerra.jpg",
      "assets/fotos/f7/Lucas Godoy, Elias Pastorino, Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra 2.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra 3.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f7/Vicente Gaitano, Ignacio Zapata, Andres Guerra, Lucas Godoy y Lucas Vidal.jpg",
      "assets/fotos/f10/Andres Guerra 2.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Lorenzo Camara, Facundo Munchs y Ignacio Zapata.jpg",
      "assets/fotos/f10/Andres Guerra, Lucas Godoy y Vicente Gaitano.jpg",
      "assets/fotos/f10/Andres Guerra.jpg",
      "assets/fotos/f10/Ignacio Zapata, Andres Guerra y Lorenzo Camara.jpg",
      "assets/fotos/f10/Mauro Cabrera y Andres Guerra.jpg"
    ],
    "Brandon": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Brandon Almenarez 2.jpg",
      "assets/fotos/f1/Brandon Almenarez y Matias Gonzalez.jpg",
      "assets/fotos/f1/Brandon Almenarez.jpg",
      "assets/fotos/f1/Fernando Garcia y Brandon Almenarez.jpg",
      "assets/fotos/f1/Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f1/Sebastian Torena, Ezequiel Arrizabalaga, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Brandon Almenarez 2.jpg",
      "assets/fotos/f2/Brandon Almenarez.jpg",
      "assets/fotos/f2/Fernando Garcia, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Sebastian Torena, Ezequiel Arrizabalaga, Agustín Rebollo, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f4/Brandon Almenarez y Matias Gonzalez.jpg",
      "assets/fotos/f5/Brandon Almenarez, Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f5/Brandon Almenarez, Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f6/Brandon Almenarez.jpg",
      "assets/fotos/f6/Elias Pastorino, Ignacio Luy y Brandon Almenarez.jpg",
      "assets/fotos/f6/Martin Sena, Andres Guerra, Facundo Munchs, Brandon Almenarez y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f7/Brandon Almenarez 2.jpg",
      "assets/fotos/f7/Brandon Almenarez 3.jpg",
      "assets/fotos/f7/Brandon Almenarez 4.jpg",
      "assets/fotos/f7/Brandon Almenarez y Lucas Vidal.jpg",
      "assets/fotos/f8/Brandon Almenarez 2.jpg",
      "assets/fotos/f8/Brandon Almenarez 3.jpg",
      "assets/fotos/f8/Brandon Almenarez.jpg",
      "assets/fotos/f8/Elias Pastorino, Agustin Rebollo y Brandon Almenarez.jpg",
      "assets/fotos/f8/Elias Pastorino, Brandon Almenarez y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Julian Rios, Tomas Jubin, Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f9/Brandon Almenarez 2.jpg",
      "assets/fotos/f9/Brandon Almenarez 3.jpg",
      "assets/fotos/f9/Brandon Almenarez.jpg",
      "assets/fotos/f9/Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f9/Matias Gonzalez y Brandon Almernarez.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez 2.jpg",
      "assets/fotos/f10/Brandon Almenarez 3.jpg",
      "assets/fotos/f10/Brandon Almenarez 4.jpg",
      "assets/fotos/f10/Brandon Almenarez 5.jpg",
      "assets/fotos/f10/Brandon Almenarez 6.jpg",
      "assets/fotos/f10/Brandon Almenarez y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez y Tomas Jubin.jpg",
      "assets/fotos/f10/Brandon Almenarez, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios y Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez 2.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios, Martin Sena y Brandon Almenarez.jpg",
      "assets/fotos/f10/Mauro Cabrera y Brandon Almenarez.jpg",
      "assets/fotos/f10/Vicente Gaitano, Matias Gonzalez, Tomas Jubin y Brandon Almenarez.jpg"
    ],
    "Diego": [
      "assets/fotos/f1/Diego Friedrich y Fabian Couto.jpg",
      "assets/fotos/f1/Diego Friedrich.jpg",
      "assets/fotos/f1/Fernando Garcia, Facundo Munchs, Julian Rios y Diego Friedrich.jpg",
      "assets/fotos/f1/Sebastian Torena y Diego Friedrich.jpg",
      "assets/fotos/f3/Diego Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f3/Diego Friedrich y Sebastian Torena.jpg",
      "assets/fotos/f4/Diego Friedrich.jpg",
      "assets/fotos/f5/Diego Friedrich, Martin Negrin y Mariano Perdomo.jpg",
      "assets/fotos/f5/Fabian Couto, Ignacio Luy y Diego Friedrich.jpg",
      "assets/fotos/f7/Andres Guerra, Lucas Vidal, Martin Sena, Matias Gonzalez y Diego Friedrich.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f9/Elias Pastorino y Diego Friedrich.jpg"
    ],
    "Elias": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f2/Elias Pastorino 1.jpg",
      "assets/fotos/f2/Elias Pastorino 2.jpg",
      "assets/fotos/f2/Elias Pastorino 3.jpg",
      "assets/fotos/f2/Elias Pastorino 4.jpg",
      "assets/fotos/f2/Elias Pastorino 5.jpg",
      "assets/fotos/f2/Elias Pastorino 6.jpg",
      "assets/fotos/f2/Elias Pastorino y Lucas Vidal.jpg",
      "assets/fotos/f2/Elias Pastorino, Fernando Garcia y Franco Friedrich.jpg",
      "assets/fotos/f2/Elias Pastorino, Franco Irisarri y Ignacio Zapata.jpg",
      "assets/fotos/f2/Elias Pastorino, Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f2/Elias Pastorino.jpg",
      "assets/fotos/f2/Lucas Vidal y Elias Pastorino.jpg",
      "assets/fotos/f2/Lucas Vidal, Sebastian Barisone, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f2/Matias Gonzalez y Elias Pastorino.jpg",
      "assets/fotos/f3/Elias Pastorino 2.jpg",
      "assets/fotos/f3/Elias Pastorino y Franco Irisarri.jpg",
      "assets/fotos/f3/Elias Pastorino.jpg",
      "assets/fotos/f3/Franco Irisarri y Elias Pastorino.jpg",
      "assets/fotos/f4/Elias Pastorino 2.jpg",
      "assets/fotos/f4/Elias Pastorino y Franco Irisarri.jpg",
      "assets/fotos/f4/Elias Pastorino.jpg",
      "assets/fotos/f4/Ignacio Luy y Elias Pastorino.jpg",
      "assets/fotos/f4/Ignacio Zapata y Elias Pastorino.jpg",
      "assets/fotos/f5/Brandon Almenarez, Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino y Mauro Cabrera.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f5/Elias Pastorino.jpg",
      "assets/fotos/f5/Facundo Munchs y Elias Pastorino.jpg",
      "assets/fotos/f5/Facundo Munchs, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f5/Matias Gonzalez, Franco Friedrich, Elias Pastorino y Tomas Jubin.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena 2.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena.jpg",
      "assets/fotos/f6/Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f6/Elias Pastorino, Ignacio Luy y Brandon Almenarez.jpg",
      "assets/fotos/f7/Elias Pastorino 2.jpg",
      "assets/fotos/f7/Elias Pastorino, Franco Irisarri, Martin Sena y Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Elias Pastorino, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f7/Elias Pastorino, Martin Sena, Ezequiel Muñoz y Ignacio Zapata.jpg",
      "assets/fotos/f7/Elias Pastorino.jpg",
      "assets/fotos/f7/Lucas Godoy, Elias Pastorino, Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f7/Mauro Cabrera y Elias Pastorino.jpg",
      "assets/fotos/f8/Agustin Rebollo, Elias Pastorino, Martin Negrin y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Elias Pastorino 2.jpg",
      "assets/fotos/f8/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f8/Elias Pastorino, Agustin Rebollo y Brandon Almenarez.jpg",
      "assets/fotos/f8/Elias Pastorino, Brandon Almenarez y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Elias Pastorino.jpg",
      "assets/fotos/f8/Ezequiel Muñoz y Elias Pastorino.jpg",
      "assets/fotos/f8/Vicente Gaitano, Franco Friedrich y Elias Pastorino.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f9/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Elias Pastorino.jpg",
      "assets/fotos/f9/Ezequiel Muñoz y Elias Pastorino.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Elias Pastorino 2.jpg",
      "assets/fotos/f10/Elias Pastorino 3.jpg",
      "assets/fotos/f10/Elias Pastorino 4.jpg",
      "assets/fotos/f10/Elias Pastorino 5.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz 2.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz 3.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Godoy 2.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Godoy.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Vidal.jpg",
      "assets/fotos/f10/Elias Pastorino y Martin Sena.jpg",
      "assets/fotos/f10/Elias Pastorino y Matias Gonzalez.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Mauro Cabrera.jpg",
      "assets/fotos/f10/Elias Pastorino, Matias Gonzalez y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Elias Pastorino.jpg",
      "assets/fotos/f10/Enzo Gaione, Elias Pastorino y Julian Rios.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga y Elias Pastorino.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Elias Pastorino, Matias Gonzalez, Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Ezequiel Arrizabalaga y Elias Pastorino.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Martin Sena y Elias Pastorino.jpg",
      "assets/fotos/f10/Franco Friedrich, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Lorenzo Camara, Lucas Godoy y Elias Pastorino.jpg",
      "assets/fotos/f10/Lucas Godoy y Elias Pastorino.jpg",
      "assets/fotos/f10/Lucas Vidal y Elias Pastorino.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich 2.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Lucas Vidal, Ezequiel Muñoz,Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Matias Gonzalez y Elias Pastorino.jpg",
      "assets/fotos/f10/Mauro Cabrera, Elias Pastorino y Matias Gonzalez.jpg"
    ],
    "Enzo": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Sebastian Torena, Ezequiel Arrizabalaga, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Enzo Gaione y Franco Friedrich.jpg",
      "assets/fotos/f2/Enzo Gaione y Matias Gonzalez.jpg",
      "assets/fotos/f2/Enzo Gaione.jpg",
      "assets/fotos/f2/Fernando Garcia, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Sebastian Torena, Ezequiel Arrizabalaga, Agustín Rebollo, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f4/Enzo Gaione 2.jpg",
      "assets/fotos/f4/Enzo Gaione 3.jpg",
      "assets/fotos/f4/Enzo Gaione 4.jpg",
      "assets/fotos/f4/Enzo Gaione, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f4/Enzo Gaione.jpg",
      "assets/fotos/f4/Matias Gonzalez, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f5/Vicente Gaitano y Enzo Gaione.jpg",
      "assets/fotos/f6/Enzo Gaione 2.jpg",
      "assets/fotos/f6/Enzo Gaione, Matias Gonzalez y Martin Negrin.jpg",
      "assets/fotos/f6/Enzo Gaione, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f6/Enzo Gaione, Vicente Gaitano, Tomas Jubin y Franco Irisarri.jpg",
      "assets/fotos/f6/Enzo Gaione.jpg",
      "assets/fotos/f6/Mauro Cabrera y Enzo Gaione 2.jpg",
      "assets/fotos/f6/Mauro Cabrera y Enzo Gaione.jpg",
      "assets/fotos/f6/Mauro Cabrera, Enzo Gaione y Vicente Gaitano.jpg",
      "assets/fotos/f7/Enzo Gaione.jpg",
      "assets/fotos/f8/Enzo Gaione y Agustin Rebollo.jpg",
      "assets/fotos/f8/Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f8/Mauro Cabrera, Martin Sena y Enzo Gaione.jpg",
      "assets/fotos/f10/Enzo Gaione 2.jpg",
      "assets/fotos/f10/Enzo Gaione y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f10/Enzo Gaione y Julian Rios.jpg",
      "assets/fotos/f10/Enzo Gaione y Lucas Vidal.jpg",
      "assets/fotos/f10/Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f10/Enzo Gaione, Elias Pastorino y Julian Rios.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 2.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 3.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena.jpg",
      "assets/fotos/f10/Enzo Gaione.jpg",
      "assets/fotos/f10/Martin Sena y Enzo Gaione.jpg"
    ],
    "Fabian Couto": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f1/Diego Friedrich y Fabian Couto.jpg",
      "assets/fotos/f1/Fabian Couto y Mauro Cabrera.jpg",
      "assets/fotos/f1/Fabián Couto, Franco Irisarri y Facundo Munchs.jpg",
      "assets/fotos/f2/Fabian Couto y Sebastian Torena.jpg",
      "assets/fotos/f2/Sebastian Torena, Renzo Soliwoda, Fabian Couto y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f5/Fabian Couto y Ignacio Luy.jpg",
      "assets/fotos/f5/Fabian Couto, Ignacio Luy y Diego Friedrich.jpg",
      "assets/fotos/f7/Fabian Couto.jpg",
      "assets/fotos/f8/Fabian Couto y Martin Sena.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f8/Mauro Cabrera y Fabian Couto.jpg"
    ],
    "Facu Munchs": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Fabián Couto, Franco Irisarri y Facundo Munchs.jpg",
      "assets/fotos/f1/Facundo Munchs 2.jpg",
      "assets/fotos/f1/Facundo Munchs 3.jpg",
      "assets/fotos/f1/Facundo Munchs 4.jpg",
      "assets/fotos/f1/Facundo Munchs 5.jpg",
      "assets/fotos/f1/Facundo Munchs y Franco Irisarri.jpg",
      "assets/fotos/f1/Facundo Munchs.jpg",
      "assets/fotos/f1/Fernando Garcia, Facundo Munchs, Julian Rios y Diego Friedrich.jpg",
      "assets/fotos/f2/Facundo Munchs.jpg",
      "assets/fotos/f2/Franco Irisarri, Facundo Munchs, Franco Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f5/Facundo Munchs 2.jpg",
      "assets/fotos/f5/Facundo Munchs 3.jpg",
      "assets/fotos/f5/Facundo Munchs y Elias Pastorino.jpg",
      "assets/fotos/f5/Facundo Munchs y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f5/Facundo Munchs y Ezequiel Muñoz.jpg",
      "assets/fotos/f5/Facundo Munchs, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f5/Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f5/Facundo Munchs.jpg",
      "assets/fotos/f5/Ignacio Luy, Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f5/Sebastian Barisone, Lorenzo Camara, Facundo Munchs y Franco Friedrich.jpg",
      "assets/fotos/f6/Facundo Munchs 2.jpg",
      "assets/fotos/f6/Facundo Munchs.jpg",
      "assets/fotos/f6/Martin Sena, Andres Guerra, Facundo Munchs, Brandon Almenarez y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f6/Martin Sena, Facundo Munchs y Vicente Gaitano.jpg",
      "assets/fotos/f7/Facundo Munchs, Ezequiel Muñoz y Andres Guerra.jpg",
      "assets/fotos/f7/Facundo Munchs.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Lorenzo Camara, Facundo Munchs y Ignacio Zapata.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga, Facundo Munchs, Ignacio Zapata, Agustin Rebollo y Vicente Gaitano.jpg",
      "assets/fotos/f10/Facundo Munchs y Vicente Gaitano.jpg"
    ],
    "Franco F": [
      "assets/fotos/f1/Franco Friedrich 2.jpg",
      "assets/fotos/f1/Franco Friedrich y Julian Rios.jpg",
      "assets/fotos/f1/Franco Friedrich y Sebastian Torena.jpg",
      "assets/fotos/f1/Franco Friedrich.jpg",
      "assets/fotos/f1/Matias Gonzalez y Franco Friedrich.jpg",
      "assets/fotos/f2/Elias Pastorino, Fernando Garcia y Franco Friedrich.jpg",
      "assets/fotos/f2/Enzo Gaione y Franco Friedrich.jpg",
      "assets/fotos/f2/Franco Friedrich 2.jpg",
      "assets/fotos/f2/Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f2/Franco Friedrich.jpg",
      "assets/fotos/f2/Franco Irisarri, Facundo Munchs, Franco Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f2/Lucas Vidal, Sebastian Barisone, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f3/Franco Friedrich 1.jpg",
      "assets/fotos/f3/Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f3/Franco Friedrich.jpg",
      "assets/fotos/f3/Mauro Cabrera, Franco Friedrich, Matias Gonzalez y Lucas Vidal.jpg",
      "assets/fotos/f4/Franco Friedrich 2.jpg",
      "assets/fotos/f4/Franco Friedrich 3.jpg",
      "assets/fotos/f4/Franco Friedrich 4.jpg",
      "assets/fotos/f4/Franco Friedrich 5.jpg",
      "assets/fotos/f4/Franco Friedrich y Mauro Cabrera 2.jpg",
      "assets/fotos/f4/Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f4/Franco Friedrich.jpg",
      "assets/fotos/f4/Ignacio Zapata, Mauro Cabrera, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f4/Julian Rios, Mauro Cabrera, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich y Ignacio Zapata.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich, Mauro Cabrera y Ignacio Zapata.jpg",
      "assets/fotos/f4/Mauro Cabrera y Franco Friedrich.jpg",
      "assets/fotos/f4/Sebastian Barisone, Mauro Cabrera, Franco Irisarri, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f5/Brandon Almenarez, Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f5/Facundo Munchs, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f5/Lorenzo Camara, Franco Irisarri y Franco Friedrich.jpg",
      "assets/fotos/f5/Matias Gonzalez, Franco Friedrich, Elias Pastorino y Tomas Jubin.jpg",
      "assets/fotos/f5/Sebastian Barisone, Lorenzo Camara, Facundo Munchs y Franco Friedrich.jpg",
      "assets/fotos/f6/Franco Friedrich.jpg",
      "assets/fotos/f8/Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f8/Franco Friedrich 2.jpg",
      "assets/fotos/f8/Franco Friedrich 3.jpg",
      "assets/fotos/f8/Franco Friedrich y Martin Sena.jpg",
      "assets/fotos/f8/Franco Friedrich.jpg",
      "assets/fotos/f8/Julian Rios, Tomas Jubin, Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich 2.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich 3.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f8/Martin Sena, Lucas Godoy, Julian Rios y Franco Friedrich.jpg",
      "assets/fotos/f8/Vicente Gaitano, Franco Friedrich y Elias Pastorino.jpg",
      "assets/fotos/f9/Fernando Garcia y Franco Friedrich.jpg",
      "assets/fotos/f9/Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f9/Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f9/Franco Friedrich, Lucas Godoy y Fernando Garcia.jpg",
      "assets/fotos/f9/Lucas Godoy y Franco Friedrich.jpg",
      "assets/fotos/f9/Martin Sena, Lucas Godoy y Franco Friedrich.jpg",
      "assets/fotos/f10/Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Franco Friedrich.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Elias Pastorino, Matias Gonzalez, Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f10/Franco Friedrich 2.jpg",
      "assets/fotos/f10/Franco Friedrich 3.jpg",
      "assets/fotos/f10/Franco Friedrich 4.jpg",
      "assets/fotos/f10/Franco Friedrich 5.jpg",
      "assets/fotos/f10/Franco Friedrich 6.jpg",
      "assets/fotos/f10/Franco Friedrich 7.jpg",
      "assets/fotos/f10/Franco Friedrich 8.jpg",
      "assets/fotos/f10/Franco Friedrich, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Franco Friedrich.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich 2.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Lucas Vidal, Ezequiel Muñoz,Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena y Feanco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena, Franco Friedrich, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Mauro Cabera y Franco Friedrich.jpg"
    ],
    "Franco Irri": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Fabián Couto, Franco Irisarri y Facundo Munchs.jpg",
      "assets/fotos/f1/Facundo Munchs y Franco Irisarri.jpg",
      "assets/fotos/f1/Franco Irisarri y Fernando Garcia.jpg",
      "assets/fotos/f1/Franco Irisarri.jpg",
      "assets/fotos/f2/Elias Pastorino, Franco Irisarri y Ignacio Zapata.jpg",
      "assets/fotos/f2/Franco Irisarri, Facundo Munchs, Franco Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f2/Franco Irisarri, Matias Gonzalez, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Franco Irisarri.jpg",
      "assets/fotos/f2/Lucas Vidal y Franco Irisarri.jpg",
      "assets/fotos/f3/Elias Pastorino y Franco Irisarri.jpg",
      "assets/fotos/f3/Franco Irisarri y Elias Pastorino.jpg",
      "assets/fotos/f3/Franco Irisarri, Matias Gonzalez y Ignacio Zapata.jpg",
      "assets/fotos/f3/Franco Irisarri.jpg",
      "assets/fotos/f3/Vicente Gaitano, Sebastian Barisone y Franco Irisarri.jpg",
      "assets/fotos/f4/Elias Pastorino y Franco Irisarri.jpg",
      "assets/fotos/f4/Franco Irisarri.jpg",
      "assets/fotos/f4/Sebastian Barisone, Mauro Cabrera, Franco Irisarri, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f5/Franco Irisarri.jpg",
      "assets/fotos/f5/Lorenzo Camara, Franco Irisarri y Franco Friedrich.jpg",
      "assets/fotos/f6/Enzo Gaione, Vicente Gaitano, Tomas Jubin y Franco Irisarri.jpg",
      "assets/fotos/f6/Franco Irisarri 2.jpg",
      "assets/fotos/f6/Franco Irisarri 3.jpg",
      "assets/fotos/f6/Franco Irisarri y Mauro Cabrera.jpg",
      "assets/fotos/f6/Franco Irisarri y Vicente Gaitano.jpg",
      "assets/fotos/f6/Franco Irisarri, Mauro Cabrera y Martin Sena.jpg",
      "assets/fotos/f6/Franco Irisarri.jpg",
      "assets/fotos/f6/Martin Sena y Franco Irisarri.jpg",
      "assets/fotos/f7/Elias Pastorino, Franco Irisarri, Martin Sena y Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Elias Pastorino, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f7/Franco Irisarri 2.jpg",
      "assets/fotos/f7/Franco Irisarri.jpg",
      "assets/fotos/f7/Vicente Gaitano y Franco Irisarri.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f9/Ezequiel Muñoz y Franco Irisarri.jpg"
    ],
    "Ignacio Luy": [
      "assets/fotos/f3/Ignacio Luy y Ignacio Zapata.jpg",
      "assets/fotos/f4/Ignacio Luy y Elias Pastorino.jpg",
      "assets/fotos/f5/Brandon Almenarez, Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Ignacio Luy.jpg",
      "assets/fotos/f5/Fabian Couto y Ignacio Luy.jpg",
      "assets/fotos/f5/Fabian Couto, Ignacio Luy y Diego Friedrich.jpg",
      "assets/fotos/f5/Ignacio Luy, Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f5/Ignacio Luy.jpg",
      "assets/fotos/f6/Elias Pastorino y Ignacio Luy.jpg",
      "assets/fotos/f6/Elias Pastorino, Ignacio Luy y Brandon Almenarez.jpg",
      "assets/fotos/f6/Ignacio Luy 2.jpg",
      "assets/fotos/f6/Ignacio Luy 3.jpg",
      "assets/fotos/f6/Ignacio Luy.jpg",
      "assets/fotos/f6/Tomas Jubin, Matias Gonzalez y Ignacio Luy.jpg",
      "assets/fotos/f8/Ezequiel Muñoz y Ignacio Luy.jpg",
      "assets/fotos/f8/Ignacio Luy, Martin Negrin, Mauro Cabrera, Ignacio Zapata y Sebastian Barisone.jpg",
      "assets/fotos/f8/Sebastián Barisone, Lucas Godoy y Ignacio Luy.jpg"
    ],
    "Jubin": [
      "assets/fotos/f1/Martin Sena y Tomas Jubin.jpg",
      "assets/fotos/f1/Martin Sena, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f1/Sebastian Torena, Fernando Garcia, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f1/Tomas Jubin 2.jpg",
      "assets/fotos/f1/Tomas Jubin 3.jpg",
      "assets/fotos/f1/Tomas Jubin.jpg",
      "assets/fotos/f2/Tomas Jubin 2.jpg",
      "assets/fotos/f2/Tomas Jubin 3.jpg",
      "assets/fotos/f2/Tomas Jubin 4.jpg",
      "assets/fotos/f2/Tomas Jubin.jpg",
      "assets/fotos/f3/Lucas Vidal y Tomas Jubin.jpg",
      "assets/fotos/f3/Tomas Jubin.jpg",
      "assets/fotos/f4/Enzo Gaione, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f4/Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f4/Matias Gonzalez, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f4/Tomas Jubin 2.jpg",
      "assets/fotos/f4/Tomas Jubin 3.jpg",
      "assets/fotos/f4/Tomas Jubin.jpg",
      "assets/fotos/f5/Elias Pastorino, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f5/Matias Gonzalez, Franco Friedrich, Elias Pastorino y Tomas Jubin.jpg",
      "assets/fotos/f5/Tomas Jubin.jpg",
      "assets/fotos/f6/Enzo Gaione, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f6/Enzo Gaione, Vicente Gaitano, Tomas Jubin y Franco Irisarri.jpg",
      "assets/fotos/f6/Martin Sena, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f6/Tomas Jubin 2.jpg",
      "assets/fotos/f6/Tomas Jubin 3.jpg",
      "assets/fotos/f6/Tomas Jubin 4.jpg",
      "assets/fotos/f6/Tomas Jubin, Matias Gonzalez y Ignacio Luy.jpg",
      "assets/fotos/f6/Tomas Jubin.jpg",
      "assets/fotos/f7/Tomas Jubin 2.jpg",
      "assets/fotos/f7/Tomas Jubin 3.jpg",
      "assets/fotos/f7/Tomas Jubin 4.jpg",
      "assets/fotos/f7/Tomas Jubin 5.jpg",
      "assets/fotos/f7/Tomas Jubin 6.jpg",
      "assets/fotos/f7/Tomas Jubin.jpg",
      "assets/fotos/f8/Agustin Rebollo y Tomas Jubin.jpg",
      "assets/fotos/f8/Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f8/Ignacio Zapata, Sebastian Barisone y Tomas Jubin.jpg",
      "assets/fotos/f8/Julian Rios, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f8/Julian Rios, Tomas Jubin, Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f8/Tomas Jubin.jpg",
      "assets/fotos/f9/Tomas Jubin 2.jpg",
      "assets/fotos/f9/Tomas Jubin 3.jpg",
      "assets/fotos/f9/Tomas Jubin 4.jpg",
      "assets/fotos/f9/Tomas Jubin.jpg",
      "assets/fotos/f9/Vicente Gaitano y Tomas Jubin.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez y Tomas Jubin.jpg",
      "assets/fotos/f10/Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f10/Julian Rios y Tomas Jubin.jpg",
      "assets/fotos/f10/Lucas Vidal y Tomas Jubin.jpg",
      "assets/fotos/f10/Martin Sena, Mauro Cabrera y Tomas Jubin.jpg",
      "assets/fotos/f10/Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f10/Tomas Jubin 2.jpg",
      "assets/fotos/f10/Tomas Jubin 3.jpg",
      "assets/fotos/f10/Tomas Jubin 4.jpg",
      "assets/fotos/f10/Tomas Jubin 5.jpg",
      "assets/fotos/f10/Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f10/Tomas Jubin y Mauro Cabrera.jpg",
      "assets/fotos/f10/Tomas Jubin, Agustin Rebollo y Ignacio Zapata.jpg",
      "assets/fotos/f10/Tomas Jubin.jpg",
      "assets/fotos/f10/Vicente Gaitano, Matias Gonzalez, Tomas Jubin y Brandon Almenarez.jpg"
    ],
    "Juli Rios": [
      "assets/fotos/f1/Fernando Garcia, Facundo Munchs, Julian Rios y Diego Friedrich.jpg",
      "assets/fotos/f1/Franco Friedrich y Julian Rios.jpg",
      "assets/fotos/f1/Julian Rios 2.jpg",
      "assets/fotos/f1/Julian Rios.jpg",
      "assets/fotos/f1/Mauro Cabrera, Julian Rios y Fernando Garcia.jpg",
      "assets/fotos/f3/Julian Rios 2.jpg",
      "assets/fotos/f3/Julian Rios 3.jpg",
      "assets/fotos/f3/Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f3/Julian Rios.jpg",
      "assets/fotos/f3/Matias Gonzalez y Julian Rios 2.jpg",
      "assets/fotos/f3/Matias Gonzalez y Julian Rios.jpg",
      "assets/fotos/f3/Matias Gonzalez, Mauro Cabrera y Julian Rios.jpg",
      "assets/fotos/f4/Julian Rios y Mauro Cabrera.jpg",
      "assets/fotos/f4/Julian Rios, Mauro Cabrera, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f4/Julian Rios.jpg",
      "assets/fotos/f7/Julian Rios 2.jpg",
      "assets/fotos/f7/Julian Rios 3.jpg",
      "assets/fotos/f7/Julian Rios 4.jpg",
      "assets/fotos/f7/Julian Rios.jpg",
      "assets/fotos/f8/Ignacio Zapata, Martin Sena y Julian Rios.jpg",
      "assets/fotos/f8/Julian Rios, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f8/Julian Rios, Tomas Jubin, Franco Friedrich y Brandon Almenarez.jpg",
      "assets/fotos/f8/Martin Sena, Lucas Godoy, Julian Rios y Franco Friedrich.jpg",
      "assets/fotos/f10/Enzo Gaione y Julian Rios.jpg",
      "assets/fotos/f10/Enzo Gaione, Elias Pastorino y Julian Rios.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 2.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 3.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena.jpg",
      "assets/fotos/f10/Julian Rios 2.jpg",
      "assets/fotos/f10/Julian Rios 3.jpg",
      "assets/fotos/f10/Julian Rios y Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Julian Rios y Martin Sena.jpg",
      "assets/fotos/f10/Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f10/Julian Rios y Tomas Jubin.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez 2.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios, Martin Sena y Brandon Almenarez.jpg",
      "assets/fotos/f10/Julian Rios.jpg",
      "assets/fotos/f10/Martin Sena, Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f10/Matias Gonzalez y Julian Rios.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena, Franco Friedrich, Julian Rios y Lucas Vidal.jpg"
    ],
    "Lolo": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f3/Lorenzo Camara 2.jpg",
      "assets/fotos/f3/Lorenzo Camara.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f5/Lorenzo Camara 2.jpg",
      "assets/fotos/f5/Lorenzo Camara, Franco Irisarri y Franco Friedrich.jpg",
      "assets/fotos/f5/Lorenzo Camara.jpg",
      "assets/fotos/f5/Sebastian Barisone, Lorenzo Camara, Facundo Munchs y Franco Friedrich.jpg",
      "assets/fotos/f7/Agustin Rebollo, Lorenzo Camara y Andres Guerra.jpg",
      "assets/fotos/f7/Lorenzo Camara.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f10/Andres Guerra, Lorenzo Camara, Facundo Munchs y Ignacio Zapata.jpg",
      "assets/fotos/f10/Ignacio Zapata, Andres Guerra y Lorenzo Camara.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez 2.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f10/Lorenzo Camara y Matias Gonzalez.jpg",
      "assets/fotos/f10/Lorenzo Camara, Lucas Godoy y Elias Pastorino.jpg"
    ],
    "Lucas Godoy": [
      "assets/fotos/f7/Lucas Godoy 2.jpg",
      "assets/fotos/f7/Lucas Godoy, Elias Pastorino, Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Lucas Godoy.jpg",
      "assets/fotos/f7/Vicente Gaitano, Ignacio Zapata, Andres Guerra, Lucas Godoy y Lucas Vidal.jpg",
      "assets/fotos/f8/Lucas Godoy.jpg",
      "assets/fotos/f8/Martin Sena, Lucas Godoy, Julian Rios y Franco Friedrich.jpg",
      "assets/fotos/f8/Sebastián Barisone, Lucas Godoy y Ignacio Luy.jpg",
      "assets/fotos/f9/Franco Friedrich, Lucas Godoy y Fernando Garcia.jpg",
      "assets/fotos/f9/Lucas Godoy y Fernando Garcia.jpg",
      "assets/fotos/f9/Lucas Godoy y Franco Friedrich.jpg",
      "assets/fotos/f9/Lucas Godoy y Ignacio Zapata.jpg",
      "assets/fotos/f9/Lucas Godoy.jpg",
      "assets/fotos/f9/Martin Sena, Lucas Godoy y Franco Friedrich.jpg",
      "assets/fotos/f10/Andres Guerra, Lucas Godoy y Vicente Gaitano.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Godoy 2.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Godoy.jpg",
      "assets/fotos/f10/Lorenzo Camara, Lucas Godoy y Elias Pastorino.jpg",
      "assets/fotos/f10/Lucas Godoy y Elias Pastorino.jpg"
    ],
    "Mandinga": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f2/Elias Pastorino, Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f2/Ezequiel Muñoz y Sebastian Barisone.jpg",
      "assets/fotos/f2/Mauro Cabrera, Sebastian Barisone, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Ezequiel Muñoz, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f3/Ezequiel Muñoz.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f5/Facundo Munchs y Ezequiel Muñoz.jpg",
      "assets/fotos/f5/Mauro Cabrera y Ezequiel Muñoz.jpg",
      "assets/fotos/f6/Ezequiel Muñoz 2.jpg",
      "assets/fotos/f6/Ezequiel Muñoz y Martin Negrin.jpg",
      "assets/fotos/f6/Ezequiel Muñoz y Mauro Cabrera.jpg",
      "assets/fotos/f6/Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Elias Pastorino, Franco Irisarri, Martin Sena y Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Elias Pastorino, Martin Sena, Ezequiel Muñoz y Ignacio Zapata.jpg",
      "assets/fotos/f7/Ezequiel Muñoz 2.jpg",
      "assets/fotos/f7/Ezequiel Muñoz, Ignacio Zapata y Martin Sena.jpg",
      "assets/fotos/f7/Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Facundo Munchs, Ezequiel Muñoz y Andres Guerra.jpg",
      "assets/fotos/f8/Agustin Rebollo, Lucas Vidal, Martin Negrin, Ezequiel Muñoz y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Elias Pastorino, Brandon Almenarez y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Ezequiel Muñoz 2.jpg",
      "assets/fotos/f8/Ezequiel Muñoz 3.jpg",
      "assets/fotos/f8/Ezequiel Muñoz 4.jpg",
      "assets/fotos/f8/Ezequiel Muñoz y Elias Pastorino.jpg",
      "assets/fotos/f8/Ezequiel Muñoz y Ignacio Luy.jpg",
      "assets/fotos/f8/Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Lucas Vidal y Ezequiel Muñoz 2.jpg",
      "assets/fotos/f8/Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Ezequiel Muñoz y Elias Pastorino.jpg",
      "assets/fotos/f9/Ezequiel Muñoz y Franco Irisarri.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena 2.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Vicente Gaitano y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz 2.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz 3.jpg",
      "assets/fotos/f10/Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Mauro Cabrera.jpg",
      "assets/fotos/f10/Elias Pastorino, Matias Gonzalez y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 2.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 3.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 4.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 5.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 6.jpg",
      "assets/fotos/f10/Ezequiel Muñoz 7.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Franco Friedrich.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Lucas Vidal 2.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Elias Pastorino, Matias Gonzalez, Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Ezequiel Arrizabalaga y Elias Pastorino.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Martin Sena y Elias Pastorino.jpg",
      "assets/fotos/f10/Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Franco Friedrich, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Martin Sena, Lucas Vidal, Ezequiel Muñoz,Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Mauro Cabera, Lucas Vidal y Ezequiel Muñoz.jpg"
    ],
    "Mariano": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f5/Diego Friedrich, Martin Negrin y Mariano Perdomo.jpg"
    ],
    "Mati": [
      "assets/fotos/f1/Brandon Almenarez y Matias Gonzalez.jpg",
      "assets/fotos/f1/Fernando Garcia y Matias Gonzalez.jpg",
      "assets/fotos/f1/Martin Sena, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f1/Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f1/Matias Gonzalez y Franco Friedrich.jpg",
      "assets/fotos/f1/Matias Gonzalez y Martin Sena.jpg",
      "assets/fotos/f1/Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f1/Sebastian Torena, Fernando Garcia, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f1/Sebastian Torena, Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f2/Enzo Gaione y Matias Gonzalez.jpg",
      "assets/fotos/f2/Franco Irisarri, Facundo Munchs, Franco Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f2/Franco Irisarri, Matias Gonzalez, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Matias Gonzalez y Elias Pastorino.jpg",
      "assets/fotos/f2/Matias Gonzalez.jpg",
      "assets/fotos/f3/Diego Friedrich y Matias Gonzalez.jpg",
      "assets/fotos/f3/Franco Irisarri, Matias Gonzalez y Ignacio Zapata.jpg",
      "assets/fotos/f3/Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f3/Matias Gonzalez 2.jpg",
      "assets/fotos/f3/Matias Gonzalez y Julian Rios 2.jpg",
      "assets/fotos/f3/Matias Gonzalez y Julian Rios.jpg",
      "assets/fotos/f3/Matias Gonzalez, Mauro Cabrera y Julian Rios.jpg",
      "assets/fotos/f3/Matias Gonzalez.jpg",
      "assets/fotos/f3/Mauro Cabrera, Franco Friedrich, Matias Gonzalez y Lucas Vidal.jpg",
      "assets/fotos/f4/Brandon Almenarez y Matias Gonzalez.jpg",
      "assets/fotos/f4/Enzo Gaione, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f4/Matias Gonzalez 2.jpg",
      "assets/fotos/f4/Matias Gonzalez y Ignacio Zapata.jpg",
      "assets/fotos/f4/Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f4/Matias Gonzalez, Enzo Gaione y Tomas Jubin.jpg",
      "assets/fotos/f4/Matias Gonzalez.jpg",
      "assets/fotos/f5/Matias Gonzalez, Franco Friedrich, Elias Pastorino y Tomas Jubin.jpg",
      "assets/fotos/f6/Enzo Gaione, Matias Gonzalez y Martin Negrin.jpg",
      "assets/fotos/f6/Enzo Gaione, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f6/Martin Sena, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f6/Matias Gonzalez 2.jpg",
      "assets/fotos/f6/Matias Gonzalez y Vicente Gaitano.jpg",
      "assets/fotos/f6/Matias Gonzalez.jpg",
      "assets/fotos/f6/Tomas Jubin, Matias Gonzalez y Ignacio Luy.jpg",
      "assets/fotos/f7/Andres Guerra, Lucas Vidal, Martin Sena, Matias Gonzalez y Diego Friedrich.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f8/Julian Rios, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f8/Matias Gonzalez.jpg",
      "assets/fotos/f9/Matias Gonzalez 2.jpg",
      "assets/fotos/f9/Matias Gonzalez y Brandon Almernarez.jpg",
      "assets/fotos/f9/Matias Gonzalez.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Elias Pastorino y Matias Gonzalez.jpg",
      "assets/fotos/f10/Elias Pastorino, Matias Gonzalez y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Elias Pastorino, Matias Gonzalez, Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f10/Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez 2.jpg",
      "assets/fotos/f10/Julian Rios, Lorenzo Camara, Matias Gonzalez y Brandon Almenarez.jpg",
      "assets/fotos/f10/Lorenzo Camara y Matias Gonzalez.jpg",
      "assets/fotos/f10/Lucas Vidal, Matias Gonzalez y Martin Sena.jpg",
      "assets/fotos/f10/Martin Sena, Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f10/Martin Sena, Matias Gonzalez y Elias Pastorino.jpg",
      "assets/fotos/f10/Matias Gonzalez 2.jpg",
      "assets/fotos/f10/Matias Gonzalez y Julian Rios.jpg",
      "assets/fotos/f10/Matias Gonzalez y Mauro Cabrera.jpg",
      "assets/fotos/f10/Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena y Feanco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena, Franco Friedrich, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera, Elias Pastorino y Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera, Martin Sena y Matias Gonzalez.jpg",
      "assets/fotos/f10/Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f10/Vicente Gaitano y Matias Gonzalez.jpg",
      "assets/fotos/f10/Vicente Gaitano, Matias Gonzalez, Tomas Jubin y Brandon Almenarez.jpg"
    ],
    "Nando": [
      "assets/fotos/f1/Fernando Garcia y Brandon Almenarez.jpg",
      "assets/fotos/f1/Fernando Garcia y Matias Gonzalez.jpg",
      "assets/fotos/f1/Fernando Garcia y Mauro Cabrera.jpg",
      "assets/fotos/f1/Fernando Garcia, Facundo Munchs, Julian Rios y Diego Friedrich.jpg",
      "assets/fotos/f1/Franco Irisarri y Fernando Garcia.jpg",
      "assets/fotos/f1/Martin Sena y Fernando Garcia.jpg",
      "assets/fotos/f1/Mauro Cabrera, Julian Rios y Fernando Garcia.jpg",
      "assets/fotos/f1/Sebastian Torena, Fernando Garcia, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f2/Elias Pastorino, Fernando Garcia y Franco Friedrich.jpg",
      "assets/fotos/f2/Fernando Garcia y Martin Sena.jpg",
      "assets/fotos/f2/Fernando Garcia, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f9/Fernando Garcia 2.jpg",
      "assets/fotos/f9/Fernando Garcia 3.jpg",
      "assets/fotos/f9/Fernando Garcia y Franco Friedrich.jpg",
      "assets/fotos/f9/Fernando Garcia.jpg",
      "assets/fotos/f9/Franco Friedrich, Lucas Godoy y Fernando Garcia.jpg",
      "assets/fotos/f9/Lucas Godoy y Fernando Garcia.jpg"
    ],
    "Negrin": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f5/Diego Friedrich, Martin Negrin y Mariano Perdomo.jpg",
      "assets/fotos/f6/Enzo Gaione, Matias Gonzalez y Martin Negrin.jpg",
      "assets/fotos/f6/Ezequiel Muñoz y Martin Negrin.jpg",
      "assets/fotos/f8/Agustin Rebollo, Elias Pastorino, Martin Negrin y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Agustin Rebollo, Lucas Vidal, Martin Negrin, Ezequiel Muñoz y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Ignacio Luy, Martin Negrin, Mauro Cabrera, Ignacio Zapata y Sebastian Barisone.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Martin Negrin.jpg"
    ],
    "Pata": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f2/Elias Pastorino, Franco Irisarri y Ignacio Zapata.jpg",
      "assets/fotos/f3/Franco Irisarri, Matias Gonzalez y Ignacio Zapata.jpg",
      "assets/fotos/f3/Ignacio Luy y Ignacio Zapata.jpg",
      "assets/fotos/f3/Ignacio Zapata 2.jpg",
      "assets/fotos/f3/Ignacio Zapata 3.jpg",
      "assets/fotos/f3/Ignacio Zapata 4.jpg",
      "assets/fotos/f3/Ignacio Zapata.jpg",
      "assets/fotos/f4/Ignacio Zapata y Elias Pastorino.jpg",
      "assets/fotos/f4/Ignacio Zapata, Mauro Cabrera, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f4/Julian Rios, Mauro Cabrera, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich y Ignacio Zapata.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich, Mauro Cabrera y Ignacio Zapata.jpg",
      "assets/fotos/f4/Matias Gonzalez y Ignacio Zapata.jpg",
      "assets/fotos/f4/Sebastian Barisone, Mauro Cabrera, Franco Irisarri, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f7/Elias Pastorino, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f7/Elias Pastorino, Martin Sena, Ezequiel Muñoz y Ignacio Zapata.jpg",
      "assets/fotos/f7/Ezequiel Muñoz, Ignacio Zapata y Martin Sena.jpg",
      "assets/fotos/f7/Ignacio Zapata y Martin Sena.jpg",
      "assets/fotos/f7/Ignacio Zapata y Mauro Cabrera.jpg",
      "assets/fotos/f7/Ignacio Zapata.jpg",
      "assets/fotos/f7/Vicente Gaitano, Ignacio Zapata, Andres Guerra, Lucas Godoy y Lucas Vidal.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f8/Ignacio Luy, Martin Negrin, Mauro Cabrera, Ignacio Zapata y Sebastian Barisone.jpg",
      "assets/fotos/f8/Ignacio Zapata, Martin Sena y Julian Rios.jpg",
      "assets/fotos/f8/Ignacio Zapata, Sebastian Barisone y Tomas Jubin.jpg",
      "assets/fotos/f8/Ignacio Zapata.jpg",
      "assets/fotos/f8/Sebastian Barisone y Ignacio Zapata.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Ignacio Zapata 2.jpg",
      "assets/fotos/f9/Ignacio Zapata 3.jpg",
      "assets/fotos/f9/Ignacio Zapata 4.jpg",
      "assets/fotos/f9/Ignacio Zapata 5.jpg",
      "assets/fotos/f9/Ignacio Zapata 6.jpg",
      "assets/fotos/f9/Ignacio Zapata 7.jpg",
      "assets/fotos/f9/Ignacio Zapata 8.jpg",
      "assets/fotos/f9/Ignacio Zapata.jpg",
      "assets/fotos/f9/Lucas Godoy y Ignacio Zapata.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Lorenzo Camara, Facundo Munchs y Ignacio Zapata.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga, Facundo Munchs, Ignacio Zapata, Agustin Rebollo y Vicente Gaitano.jpg",
      "assets/fotos/f10/Ignacio Zapata, Andres Guerra y Lorenzo Camara.jpg",
      "assets/fotos/f10/Tomas Jubin, Agustin Rebollo y Ignacio Zapata.jpg"
    ],
    "Pato": [
      "assets/fotos/f1/Fabian Couto y Mauro Cabrera.jpg",
      "assets/fotos/f1/Fernando Garcia y Mauro Cabrera.jpg",
      "assets/fotos/f1/Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f1/Mauro Cabrera, Julian Rios y Fernando Garcia.jpg",
      "assets/fotos/f1/Mauro Cabrera.jpg",
      "assets/fotos/f1/Sebastian Torena, Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f2/Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena, Lucas Vidal y Renzo Soliwoda.jpg",
      "assets/fotos/f2/Mauro Cabrera, Sebastian Barisone, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Matias Gonzalez, Mauro Cabrera y Julian Rios.jpg",
      "assets/fotos/f3/Mauro Cabrera 2.jpg",
      "assets/fotos/f3/Mauro Cabrera 3.jpg",
      "assets/fotos/f3/Mauro Cabrera, Franco Friedrich, Matias Gonzalez y Lucas Vidal.jpg",
      "assets/fotos/f3/Mauro Cabrera.jpg",
      "assets/fotos/f4/Franco Friedrich y Mauro Cabrera 2.jpg",
      "assets/fotos/f4/Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f4/Ignacio Zapata, Mauro Cabrera, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f4/Julian Rios y Mauro Cabrera.jpg",
      "assets/fotos/f4/Julian Rios, Mauro Cabrera, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich, Mauro Cabrera y Ignacio Zapata.jpg",
      "assets/fotos/f4/Mauro Cabrera 2.jpg",
      "assets/fotos/f4/Mauro Cabrera 3.jpg",
      "assets/fotos/f4/Mauro Cabrera 4.jpg",
      "assets/fotos/f4/Mauro Cabrera y Franco Friedrich.jpg",
      "assets/fotos/f4/Mauro Cabrera.jpg",
      "assets/fotos/f4/Sebastian Barisone, Mauro Cabrera, Franco Irisarri, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f5/Elias Pastorino y Mauro Cabrera.jpg",
      "assets/fotos/f5/Mauro Cabrera y Ezequiel Muñoz.jpg",
      "assets/fotos/f6/Ezequiel Muñoz y Mauro Cabrera.jpg",
      "assets/fotos/f6/Franco Irisarri y Mauro Cabrera.jpg",
      "assets/fotos/f6/Franco Irisarri, Mauro Cabrera y Martin Sena.jpg",
      "assets/fotos/f6/Mauro Cabrera y Enzo Gaione 2.jpg",
      "assets/fotos/f6/Mauro Cabrera y Enzo Gaione.jpg",
      "assets/fotos/f6/Mauro Cabrera, Enzo Gaione y Vicente Gaitano.jpg",
      "assets/fotos/f6/Mauro Cabrera.jpg",
      "assets/fotos/f7/Ignacio Zapata y Mauro Cabrera.jpg",
      "assets/fotos/f7/Mauro Cabrera 2.jpg",
      "assets/fotos/f7/Mauro Cabrera 3.jpg",
      "assets/fotos/f7/Mauro Cabrera y Elias Pastorino.jpg",
      "assets/fotos/f7/Mauro Cabrera.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f8/Ignacio Luy, Martin Negrin, Mauro Cabrera, Ignacio Zapata y Sebastian Barisone.jpg",
      "assets/fotos/f8/Mauro Cabrera y Fabian Couto.jpg",
      "assets/fotos/f8/Mauro Cabrera y Lucas Vidal.jpg",
      "assets/fotos/f8/Mauro Cabrera, Martin Sena y Enzo Gaione.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Mauro Cabrera.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Elias Pastorino, Matias Gonzalez, Franco Friedrich y Mauro Cabrera.jpg",
      "assets/fotos/f10/Lucas Vidal y Mauro Cabrera.jpg",
      "assets/fotos/f10/Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Martin Sena, Mauro Cabrera y Tomas Jubin.jpg",
      "assets/fotos/f10/Matias Gonzalez y Mauro Cabrera.jpg",
      "assets/fotos/f10/Mauro Cabera y Franco Friedrich.jpg",
      "assets/fotos/f10/Mauro Cabera, Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Mauro Cabrera 2.jpg",
      "assets/fotos/f10/Mauro Cabrera y Andres Guerra.jpg",
      "assets/fotos/f10/Mauro Cabrera y Brandon Almenarez.jpg",
      "assets/fotos/f10/Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera, Elias Pastorino y Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera, Martin Sena y Matias Gonzalez.jpg",
      "assets/fotos/f10/Mauro Cabrera.jpg",
      "assets/fotos/f10/Tomas Jubin y Mauro Cabrera.jpg"
    ],
    "Renzo": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena, Lucas Vidal y Renzo Soliwoda.jpg",
      "assets/fotos/f2/Sebastian Torena, Renzo Soliwoda, Fabian Couto y Ezequiel Arrizabalaga.jpg"
    ],
    "Seba B": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f2/Ezequiel Muñoz y Sebastian Barisone.jpg",
      "assets/fotos/f2/Lucas Vidal, Sebastian Barisone, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f2/Mauro Cabrera, Sebastian Barisone, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f3/Sebastian Barisone.jpg",
      "assets/fotos/f3/Vicente Gaitano, Sebastian Barisone y Franco Irisarri.jpg",
      "assets/fotos/f4/Sebastian Barisone 2.jpg",
      "assets/fotos/f4/Sebastian Barisone 3.jpg",
      "assets/fotos/f4/Sebastian Barisone 4.jpg",
      "assets/fotos/f4/Sebastian Barisone 5.jpg",
      "assets/fotos/f4/Sebastian Barisone 6.jpg",
      "assets/fotos/f4/Sebastian Barisone, Mauro Cabrera, Franco Irisarri, Ignacio Zapata y Franco Friedrich.jpg",
      "assets/fotos/f4/Sebastian Barisone.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena 2.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena.jpg",
      "assets/fotos/f5/Sebastian Barisone, Lorenzo Camara, Facundo Munchs y Franco Friedrich.jpg",
      "assets/fotos/f5/Sebastian Barisone.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f8/Ignacio Luy, Martin Negrin, Mauro Cabrera, Ignacio Zapata y Sebastian Barisone.jpg",
      "assets/fotos/f8/Ignacio Zapata, Sebastian Barisone y Tomas Jubin.jpg",
      "assets/fotos/f8/Sebastian Barisone 2.jpg",
      "assets/fotos/f8/Sebastian Barisone y Ignacio Zapata.jpg",
      "assets/fotos/f8/Sebastián Barisone, Lucas Godoy y Ignacio Luy.jpg",
      "assets/fotos/f8/Sebastian Barisone.jpg"
    ],
    "Seba T": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Franco Friedrich y Sebastian Torena.jpg",
      "assets/fotos/f1/Sebastian Torena 2.jpg",
      "assets/fotos/f1/Sebastian Torena 3.jpg",
      "assets/fotos/f1/Sebastian Torena 4.jpg",
      "assets/fotos/f1/Sebastian Torena 5.jpg",
      "assets/fotos/f1/Sebastian Torena 6.jpg",
      "assets/fotos/f1/Sebastian Torena 7.jpg",
      "assets/fotos/f1/Sebastian Torena 8.jpg",
      "assets/fotos/f1/Sebastian Torena 9.jpg",
      "assets/fotos/f1/Sebastian Torena y Diego Friedrich.jpg",
      "assets/fotos/f1/Sebastian Torena y Vicente Gaitano.jpg",
      "assets/fotos/f1/Sebastian Torena, Ezequiel Arrizabalaga, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f1/Sebastian Torena, Fernando Garcia, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f1/Sebastian Torena, Mauro Cabrera y Matias Gonzalez.jpg",
      "assets/fotos/f1/Sebastian Torena.jpg",
      "assets/fotos/f2/Fabian Couto y Sebastian Torena.jpg",
      "assets/fotos/f2/Sebastian Torena 2.jpg",
      "assets/fotos/f2/Sebastian Torena 3.jpg",
      "assets/fotos/f2/Sebastian Torena, Ezequiel Arrizabalaga, Agustín Rebollo, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Sebastian Torena, Renzo Soliwoda, Fabian Couto y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f2/Sebastian Torena.jpg",
      "assets/fotos/f3/Diego Friedrich y Sebastian Torena.jpg",
      "assets/fotos/f3/Ezequiel Muñoz, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg"
    ],
    "Sena": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f1/Martin Sena 2.jpg",
      "assets/fotos/f1/Martin Sena y Fernando Garcia.jpg",
      "assets/fotos/f1/Martin Sena y Tomas Jubin.jpg",
      "assets/fotos/f1/Martin Sena, Tomas Jubin y Matias Gonzalez.jpg",
      "assets/fotos/f1/Martin Sena.jpg",
      "assets/fotos/f1/Matias Gonzalez y Martin Sena.jpg",
      "assets/fotos/f2/Ezequiel Arrizabalaga y Martin Sena.jpg",
      "assets/fotos/f2/Fernando Garcia y Martin Sena.jpg",
      "assets/fotos/f2/Franco Irisarri, Matias Gonzalez, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena, Lucas Vidal y Renzo Soliwoda.jpg",
      "assets/fotos/f3/Martin Sena.jpg",
      "assets/fotos/f4/Ignacio Zapata, Mauro Cabrera, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich y Ignacio Zapata.jpg",
      "assets/fotos/f4/Martin Sena, Franco Friedrich, Mauro Cabrera y Ignacio Zapata.jpg",
      "assets/fotos/f5/Martin Sena 2.jpg",
      "assets/fotos/f5/Martin Sena.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena 2.jpg",
      "assets/fotos/f5/Sebastian Barisone, Elias Pastorino y Martin Sena.jpg",
      "assets/fotos/f6/Franco Irisarri, Mauro Cabrera y Martin Sena.jpg",
      "assets/fotos/f6/Martin Sena 2.jpg",
      "assets/fotos/f6/Martin Sena y Franco Irisarri.jpg",
      "assets/fotos/f6/Martin Sena, Andres Guerra, Facundo Munchs, Brandon Almenarez y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f6/Martin Sena, Facundo Munchs y Vicente Gaitano.jpg",
      "assets/fotos/f6/Martin Sena, Matias Gonzalez y Tomas Jubin.jpg",
      "assets/fotos/f6/Martin Sena.jpg",
      "assets/fotos/f7/Andres Guerra, Lucas Vidal, Martin Sena, Matias Gonzalez y Diego Friedrich.jpg",
      "assets/fotos/f7/Elias Pastorino, Franco Irisarri, Martin Sena y Ezequiel Muñoz.jpg",
      "assets/fotos/f7/Elias Pastorino, Martin Sena, Ezequiel Muñoz y Ignacio Zapata.jpg",
      "assets/fotos/f7/Ezequiel Muñoz, Ignacio Zapata y Martin Sena.jpg",
      "assets/fotos/f7/Ignacio Zapata y Martin Sena.jpg",
      "assets/fotos/f7/Martin Sena 2.jpg",
      "assets/fotos/f7/Martin Sena 3.jpg",
      "assets/fotos/f7/Martin Sena y Agustin Rebollo.jpg",
      "assets/fotos/f7/Martin Sena.jpg",
      "assets/fotos/f8/Fabian Couto y Martin Sena.jpg",
      "assets/fotos/f8/Franco Friedrich y Martin Sena.jpg",
      "assets/fotos/f8/Ignacio Zapata, Martin Sena y Julian Rios.jpg",
      "assets/fotos/f8/Lucas Vidal y Martin Sena.jpg",
      "assets/fotos/f8/Martin Sena 2.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich 2.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich 3.jpg",
      "assets/fotos/f8/Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f8/Martin Sena, Lucas Godoy, Julian Rios y Franco Friedrich.jpg",
      "assets/fotos/f8/Martin Sena.jpg",
      "assets/fotos/f8/Mauro Cabrera, Martin Sena y Enzo Gaione.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena 2.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Martin Sena, Lucas Godoy y Franco Friedrich.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Facundo Munchs, Ignacio Zapata, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Brandon Almenarez, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Elias Pastorino y Martin Sena.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 2.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena 3.jpg",
      "assets/fotos/f10/Enzo Gaione, Julian Rios y Martin Sena.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Martin Sena y Elias Pastorino.jpg",
      "assets/fotos/f10/Julian Rios y Martin Sena.jpg",
      "assets/fotos/f10/Julian Rios, Martin Sena y Brandon Almenarez.jpg",
      "assets/fotos/f10/Lucas Vidal y Martin Sena.jpg",
      "assets/fotos/f10/Lucas Vidal, Matias Gonzalez y Martin Sena.jpg",
      "assets/fotos/f10/Martin Sena y Enzo Gaione.jpg",
      "assets/fotos/f10/Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Martin Sena, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Julian Rios y Matias Gonzalez.jpg",
      "assets/fotos/f10/Martin Sena, Lucas Vidal, Ezequiel Muñoz,Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Martin Sena, Matias Gonzalez y Elias Pastorino.jpg",
      "assets/fotos/f10/Martin Sena, Mauro Cabrera y Tomas Jubin.jpg",
      "assets/fotos/f10/Martin Sena.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios, Martin Sena y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena y Feanco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena, Franco Friedrich, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Mauro Cabrera, Martin Sena y Matias Gonzalez.jpg"
    ],
    "staff-at": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f2/Sebastian Torena, Ezequiel Arrizabalaga, Agustín Rebollo, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f5/Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f5/Ignacio Luy, Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f7/Agustin Rebollo, Lorenzo Camara y Andres Guerra.jpg",
      "assets/fotos/f7/Martin Sena y Agustin Rebollo.jpg",
      "assets/fotos/f8/Agustin Rebollo y Tomas Jubin.jpg",
      "assets/fotos/f8/Agustin Rebollo, Elias Pastorino, Martin Negrin y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Agustin Rebollo, Lucas Vidal, Martin Negrin, Ezequiel Muñoz y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Elias Pastorino, Agustin Rebollo y Brandon Almenarez.jpg",
      "assets/fotos/f8/Enzo Gaione y Agustin Rebollo.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Agustin Rebollo 2.jpg",
      "assets/fotos/f10/Agustin Rebollo.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga, Facundo Munchs, Ignacio Zapata, Agustin Rebollo y Vicente Gaitano.jpg",
      "assets/fotos/f10/Tomas Jubin, Agustin Rebollo y Ignacio Zapata.jpg"
    ],
    "staff-dt": [
      "assets/fotos/f2/Grupo f2.jpg",
      "assets/fotos/f1/Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f1/Sebastian Torena, Ezequiel Arrizabalaga, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Ezequiel Arrizabalaga y Martin Sena.jpg",
      "assets/fotos/f2/Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f2/Sebastian Torena, Ezequiel Arrizabalaga, Agustín Rebollo, Brandon Almenarez y Enzo Gaione.jpg",
      "assets/fotos/f2/Sebastian Torena, Renzo Soliwoda, Fabian Couto y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f3/Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f4/Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f5/Brandon Almenarez, Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f5/Facundo Munchs y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f5/Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f5/Ignacio Luy, Facundo Munchs, Ezequiel Arrizabalaga y Agustin Rebollo.jpg",
      "assets/fotos/f6/Martin Sena, Andres Guerra, Facundo Munchs, Brandon Almenarez y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Agustin Rebollo, Elias Pastorino, Martin Negrin y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Agustin Rebollo, Lucas Vidal, Martin Negrin, Ezequiel Muñoz y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Fabian Couto, Sebastian Barisone, Mauro Cabrera, Ezequiel Arrizabalaga, Ignacio Zapata y Franco Irisarri.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Franco Friedrich y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f9/Martin Negrin, Ezequiel Arrizabalaga, Ignacio Zapata, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f10/Enzo Gaione y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga y Elias Pastorino.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga, Facundo Munchs, Ignacio Zapata, Agustin Rebollo y Vicente Gaitano.jpg",
      "assets/fotos/f10/Ezequiel Muñoz, Ezequiel Arrizabalaga y Elias Pastorino.jpg"
    ],
    "Vicente": [
      "assets/fotos/f1/Sebastian Torena y Vicente Gaitano.jpg",
      "assets/fotos/f3/Vicente Gaitano 2.jpg",
      "assets/fotos/f3/Vicente Gaitano 3.jpg",
      "assets/fotos/f3/Vicente Gaitano, Sebastian Barisone y Franco Irisarri.jpg",
      "assets/fotos/f3/Vicente Gaitano.jpg",
      "assets/fotos/f5/Vicente Gaitano 2.jpg",
      "assets/fotos/f5/Vicente Gaitano y Enzo Gaione.jpg",
      "assets/fotos/f5/Vicente Gaitano.jpg",
      "assets/fotos/f6/Enzo Gaione, Vicente Gaitano, Tomas Jubin y Franco Irisarri.jpg",
      "assets/fotos/f6/Franco Irisarri y Vicente Gaitano.jpg",
      "assets/fotos/f6/Martin Sena, Facundo Munchs y Vicente Gaitano.jpg",
      "assets/fotos/f6/Matias Gonzalez y Vicente Gaitano.jpg",
      "assets/fotos/f6/Mauro Cabrera, Enzo Gaione y Vicente Gaitano.jpg",
      "assets/fotos/f6/Vicente Gaitano 2.jpg",
      "assets/fotos/f6/Vicente Gaitano.jpg",
      "assets/fotos/f7/Vicente Gaitano 2.jpg",
      "assets/fotos/f7/Vicente Gaitano y Franco Irisarri.jpg",
      "assets/fotos/f7/Vicente Gaitano, Ignacio Zapata, Andres Guerra, Lucas Godoy y Lucas Vidal.jpg",
      "assets/fotos/f7/Vicente Gaitano.jpg",
      "assets/fotos/f8/Vicente Gaitano, Franco Friedrich y Elias Pastorino.jpg",
      "assets/fotos/f8/Vicente Gaitano.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ezequiel Arrizabalaga, Ignacio Zapata, Vicente Gaitano, Martin Sena, Elias Pastorino y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Agustin Rebollo, Ignacio Zapata, Ezequiel Arrizabalaga, Vicente Gaitano, Martin Negrin y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena 2.jpg",
      "assets/fotos/f9/Ezequiel Muñoz, Vicente Gaitano y Martin Sena.jpg",
      "assets/fotos/f9/Vicente Gaitano y Ezequiel Muñoz.jpg",
      "assets/fotos/f9/Vicente Gaitano y Tomas Jubin.jpg",
      "assets/fotos/f9/Vicente Gaitano.jpg",
      "assets/fotos/f10/Andres Guerra, Agustin Rebollo, Ignacio Zapata, Brandon Almenarez, Matias Gonzalez, Vicente Gaitano, Tomas Jubin, Martin Sena y Mauro Cabrera.jpg",
      "assets/fotos/f10/Andres Guerra, Lucas Godoy y Vicente Gaitano.jpg",
      "assets/fotos/f10/Ezequiel Arrizabalaga, Facundo Munchs, Ignacio Zapata, Agustin Rebollo y Vicente Gaitano.jpg",
      "assets/fotos/f10/Facundo Munchs y Vicente Gaitano.jpg",
      "assets/fotos/f10/Vicente Gaitano y Matias Gonzalez.jpg",
      "assets/fotos/f10/Vicente Gaitano, Matias Gonzalez, Tomas Jubin y Brandon Almenarez.jpg",
      "assets/fotos/f10/Vicente Gaitano.jpg"
    ],
    "Vidal": [
      "assets/fotos/f3/Grupo f3.jpg",
      "assets/fotos/f2/Elias Pastorino y Lucas Vidal.jpg",
      "assets/fotos/f2/Elias Pastorino, Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f2/Franco Irisarri, Matias Gonzalez, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Lucas Vidal 2.jpg",
      "assets/fotos/f2/Lucas Vidal 3.jpg",
      "assets/fotos/f2/Lucas Vidal 4.jpg",
      "assets/fotos/f2/Lucas Vidal 5.jpg",
      "assets/fotos/f2/Lucas Vidal y Elias Pastorino.jpg",
      "assets/fotos/f2/Lucas Vidal y Franco Irisarri.jpg",
      "assets/fotos/f2/Lucas Vidal, Sebastian Barisone, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f2/Lucas Vidal.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena y Lucas Vidal.jpg",
      "assets/fotos/f2/Mauro Cabrera, Martin Sena, Lucas Vidal y Renzo Soliwoda.jpg",
      "assets/fotos/f2/Mauro Cabrera, Sebastian Barisone, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f3/Ezequiel Muñoz, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f3/Lucas Vidal 2.jpg",
      "assets/fotos/f3/Lucas Vidal 3.jpg",
      "assets/fotos/f3/Lucas Vidal 4.jpg",
      "assets/fotos/f3/Lucas Vidal 5.jpg",
      "assets/fotos/f3/Lucas Vidal y Tomas Jubin.jpg",
      "assets/fotos/f3/Lucas Vidal.jpg",
      "assets/fotos/f3/Mauro Cabrera, Franco Friedrich, Matias Gonzalez y Lucas Vidal.jpg",
      "assets/fotos/f3/Sebastian Barisone, Lorenzo Camara, Ezequiel Muñoz, Ezequiel Arrizabalaga, Fabian Couto, Lucas Vidal y Sebastian Torena.jpg",
      "assets/fotos/f4/Lucas Vidal.jpg",
      "assets/fotos/f7/Andres Guerra y Lucas Vidal.jpg",
      "assets/fotos/f7/Andres Guerra, Lucas Vidal, Martin Sena, Matias Gonzalez y Diego Friedrich.jpg",
      "assets/fotos/f7/Brandon Almenarez y Lucas Vidal.jpg",
      "assets/fotos/f7/Lucas Godoy, Elias Pastorino, Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Lucas Vidal 2.jpg",
      "assets/fotos/f7/Lucas Vidal 3.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra 2.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra 3.jpg",
      "assets/fotos/f7/Lucas Vidal y Andres Guerra.jpg",
      "assets/fotos/f7/Lucas Vidal.jpg",
      "assets/fotos/f7/Matias Gonzalez, Andres Guerra, Lucas Vidal, Lorenzo Camara, Elias Pastorino y Diego Friedrich.jpg",
      "assets/fotos/f7/Vicente Gaitano, Ignacio Zapata, Andres Guerra, Lucas Godoy y Lucas Vidal.jpg",
      "assets/fotos/f8/Agustin Rebollo, Lucas Vidal, Martin Negrin, Ezequiel Muñoz y Ezequiel Arrizabalaga.jpg",
      "assets/fotos/f8/Lucas Vidal y Ezequiel Muñoz 2.jpg",
      "assets/fotos/f8/Lucas Vidal y Ezequiel Muñoz.jpg",
      "assets/fotos/f8/Lucas Vidal y Martin Sena.jpg",
      "assets/fotos/f8/Lucas Vidal.jpg",
      "assets/fotos/f8/Mauro Cabrera y Lucas Vidal.jpg",
      "assets/fotos/f10/Elias Pastorino y Lucas Vidal.jpg",
      "assets/fotos/f10/Elias Pastorino, Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f10/Enzo Gaione y Lucas Vidal.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Lucas Vidal 2.jpg",
      "assets/fotos/f10/Ezequiel Muñoz y Lucas Vidal.jpg",
      "assets/fotos/f10/Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Lucas Vidal 2.jpg",
      "assets/fotos/f10/Lucas Vidal 3.jpg",
      "assets/fotos/f10/Lucas Vidal 4.jpg",
      "assets/fotos/f10/Lucas Vidal y Elias Pastorino.jpg",
      "assets/fotos/f10/Lucas Vidal y Martin Sena.jpg",
      "assets/fotos/f10/Lucas Vidal y Mauro Cabrera.jpg",
      "assets/fotos/f10/Lucas Vidal y Tomas Jubin.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich 2.jpg",
      "assets/fotos/f10/Lucas Vidal, Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Lucas Vidal, Matias Gonzalez y Martin Sena.jpg",
      "assets/fotos/f10/Lucas Vidal.jpg",
      "assets/fotos/f10/Martin Sena, Lucas Vidal, Ezequiel Muñoz,Elias Pastorino y Franco Friedrich.jpg",
      "assets/fotos/f10/Matias Gonzalez, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Matias Gonzalez, Martin Sena, Franco Friedrich, Julian Rios y Lucas Vidal.jpg",
      "assets/fotos/f10/Mauro Cabera, Lucas Vidal y Ezequiel Muñoz.jpg"
    ]
  },
  "playerMinutes": {
    "amistoso": {
      "Negrin": 45,
      "Fabian Couto": 90,
      "Seba B": 50,
      "Vidal": 70,
      "Franco Irri": 65,
      "Mandinga": 45,
      "Brandon": 55,
      "Pata": 60,
      "Nando": 90,
      "Sena": 90,
      "Elias": 80,
      "Pato": 90,
      "Franco F": 70,
      "Jubin": 90
    },
    "f1": {
      "Diego": 30,
      "Negrin": 20,
      "Lolo": 55,
      "Facu Munchs": 90,
      "Fabian Couto": 35,
      "Vicente": 20,
      "Franco Irri": 60,
      "Brandon": 60,
      "Nando": 90,
      "Sena": 75,
      "Juli Rios": 45,
      "Mati": 70,
      "Pato": 70,
      "Franco F": 90,
      "Jubin": 90,
      "Seba T": 90
    },
    "f2": {
      "Facu Munchs": 25,
      "Seba B": 40,
      "Vidal": 45,
      "Franco Irri": 45,
      "Mandinga": 30,
      "Brandon": 35,
      "Pata": 50,
      "Nando": 90,
      "Enzo": 60,
      "Sena": 55,
      "Elias": 90,
      "Mati": 90,
      "Pato": 90,
      "Franco F": 90,
      "Jubin": 90,
      "Seba T": 65
    },
    "f3": {
      "Diego": 15,
      "Negrin": 10,
      "Lolo": 15,
      "Vicente": 45,
      "Seba B": 45,
      "Vidal": 45,
      "Franco Irri": 45,
      "Mandinga": 50,
      "Pata": 75,
      "Sena": 80,
      "Elias": 40,
      "Juli Rios": 90,
      "Mati": 90,
      "Pato": 90,
      "Franco F": 90,
      "Jubin": 90,
      "Ignacio Luy": 30,
      "Mariano": 10,
      "Seba T": 35
    },
    "f4": {
      "Diego": 0,
      "Lolo": 0,
      "Seba B": 90,
      "Vidal": 45,
      "Franco Irri": 60,
      "Mandinga": 25,
      "Brandon": 20,
      "Pata": 45,
      "Nando": 25,
      "Enzo": 30,
      "Sena": 70,
      "Elias": 90,
      "Juli Rios": 60,
      "Mati": 65,
      "Pato": 90,
      "Franco F": 90,
      "Jubin": 90,
      "Ignacio Luy": 30
    },
    "f5": {
      "Diego": 15,
      "Negrin": 0,
      "Lolo": 45,
      "Facu Munchs": 45,
      "Fabian Couto": 25,
      "Vicente": 45,
      "Seba B": 45,
      "Franco Irri": 45,
      "Mandinga": 65,
      "Brandon": 45,
      "Enzo": 90,
      "Sena": 45,
      "Elias": 75,
      "Mati": 90,
      "Pato": 90,
      "Franco F": 60,
      "Jubin": 90,
      "Ignacio Luy": 45,
      "Mariano": 0
    },
    "f6": {
      "Negrin": 15,
      "Lolo": 20,
      "Andres Guerra": 30,
      "Facu Munchs": 45,
      "Lucas Godoy": 30,
      "Vicente": 90,
      "Franco Irri": 75,
      "Mandinga": 60,
      "Brandon": 90,
      "Enzo": 90,
      "Sena": 90,
      "Elias": 55,
      "Mati": 70,
      "Pato": 80,
      "Jubin": 90,
      "Ignacio Luy": 60
    },
    "f7": {
      "Diego": 25,
      "Lolo": 30,
      "Andres Guerra": 30,
      "Facu Munchs": 15,
      "Lucas Godoy": 45,
      "Vicente": 45,
      "Vidal": 50,
      "Franco Irri": 40,
      "Mandinga": 65,
      "Brandon": 80,
      "Pata": 60,
      "Enzo": 90,
      "Sena": 55,
      "Elias": 90,
      "Juli Rios": 90,
      "Pato": 90,
      "Jubin": 90
    },
    "f8": {
      "Negrin": 15,
      "Fabian Couto": 30,
      "Lucas Godoy": 45,
      "Vicente": 30,
      "Seba B": 45,
      "Vidal": 60,
      "Mandinga": 75,
      "Brandon": 45,
      "Pata": 45,
      "Nando": 15,
      "Enzo": 45,
      "Sena": 90,
      "Elias": 60,
      "Juli Rios": 90,
      "Mati": 60,
      "Pato": 45,
      "Franco F": 75,
      "Jubin": 90,
      "Ignacio Luy": 30
    },
    "f9": {
      "Diego": 20,
      "Negrin": 25,
      "Lucas Godoy": 65,
      "Vicente": 70,
      "Mandinga": 90,
      "Brandon": 90,
      "Pata": 90,
      "Nando": 75,
      "Sena": 90,
      "Elias": 90,
      "Mati": 90,
      "Franco F": 90,
      "Jubin": 90
    },
    "Fecha 11": {
      "Jubin": 90,
      "Vicente": 90,
      "Brandon": 90,
      "Franco F": 90,
      "Diego": 10,
      "Elias": 90,
      "Negrin": 55,
      "Lolo": 45,
      "Franco Irri": 55,
      "Seba B": 45,
      "Pato": 90,
      "Mati": 90,
      "Mandinga": 70,
      "Lucas Godoy": 80
    },
    "Fecha 10": {
      "Jubin": 90,
      "Vicente": 10,
      "Brandon": 90,
      "Juli Rios": 80,
      "Vidal": 80,
      "Franco F": 90,
      "Elias": 85,
      "Lolo": 10,
      "Pata": 25,
      "Enzo": 45,
      "Pato": 90,
      "Mati": 90,
      "Mandinga": 60,
      "Lucas Godoy": 30,
      "Andres Guerra": 5,
      "Sena": 55
    }
  },
  "cardsByMatch": {
    "f4": [
      {
        "name": "Nando",
        "type": "red",
        "min": 25
      }
    ],
    "f5": [
      {
        "name": "Franco F",
        "type": "red",
        "min": 60
      }
    ],
    "f9": [
      {
        "name": "Nando",
        "type": "red",
        "min": 75
      }
    ],
    "Fecha 10": [
      {
        "name": "Sena",
        "type": "red",
        "min": 55
      },
      {
        "name": "Pata",
        "type": "red",
        "min": 70
      }
    ]
  }
};
